# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20180308_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetric',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
        migrations.AlterField(
            model_name='articleaccess',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
        migrations.AlterField(
            model_name='historicarticleaccess',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
    ]
