# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0022_auto_20190902_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='homepage_preprints',
            field=models.ManyToManyField(to='submission.Article'),
        ),
    ]
