# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_merge_20180716_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorassignment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
    ]
