# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0032_remove_journal_current_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='current_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_issue', to='journal.Issue'),
        ),
    ]
