# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0033_journal_current_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='articles',
        ),
    ]
