# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0035_issue_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleordering',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
        migrations.AlterField(
            model_name='pinnedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
    ]
