# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0042_auto_20190820_1040'),
        ('core', '0031_transworkflowlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransGalley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remote', models.BooleanField(default=False)),
                ('remote_file', models.URLField(blank=True, null=True)),
                ('label', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML'), ('xml', 'XML'), ('doc', 'Word (Doc)'), ('docx', 'Word (DOCX)'), ('odt', 'OpenDocument Text Document'), ('tex', 'LaTeX'), ('rtf', 'RTF')], max_length=100)),
                ('sequence', models.IntegerField(default=0)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle')),
                ('css_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_css_file', to='core.File')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.File')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='trans_images', to='core.File')),
            ],
        ),
    ]
