# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_transgalley'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transgalley',
            name='article',
        ),
        migrations.RemoveField(
            model_name='transgalley',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='transgalley',
            name='file',
        ),
        migrations.RemoveField(
            model_name='transgalley',
            name='images',
        ),
        migrations.DeleteModel(
            name='TransGalley',
        ),
    ]
