# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190820_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galley',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
    ]
