# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190826_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galley',
            name='article',
        ),
    ]
