# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_auto_20190819_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransArticleStageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_from', models.CharField(max_length=200)),
                ('stage_to', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
    ]
