# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_transarticlestagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher_notes',
            field=models.ManyToManyField(blank=True, null=True, related_name='publisher_notes', to='submission.PublisherNote'),
        ),
        migrations.AlterField(
            model_name='transarticle',
            name='publisher_notes',
            field=models.ManyToManyField(blank=True, null=True, related_name='trans_publisher_notes', to='submission.PublisherNote'),
        ),
    ]
