# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0042_auto_20190820_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transarticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='submission.TransKeyword'),
        ),
    ]
