# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0044_transkeyword_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transarticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='keywords', to='submission.TransKeyword'),
        ),
    ]
