# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0047_auto_20190820_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transarticle',
            name='render_galley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_render_galley', to='core.Galley'),
        ),
    ]
