# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0048_auto_20190826_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transarticle',
            name='large_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_image_file', to='core.File'),
        ),
        migrations.AlterField(
            model_name='transarticle',
            name='thumbnail_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trans_thumbnail_file', to='core.File'),
        ),
    ]
