# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0049_auto_20190826_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenauthor',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
    ]
