# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0051_auto_20190902_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transarticleauthororder',
            name='article',
        ),
        migrations.RemoveField(
            model_name='transarticleauthororder',
            name='author',
        ),
        migrations.AlterField(
            model_name='articleauthororder',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.TransArticle'),
        ),
        migrations.DeleteModel(
            name='TransArticleAuthorOrder',
        ),
    ]
